# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: CSP_Agent

resources:
  repositories:
    - repository: templates
      type: github
      name: Yamaha-Motor-da-Amazonia/gk-csp-templates-pipelines
      endpoint: GitHub connection CSP
stages: 
- template: template-node.yml@templates
