# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: Build
  displayName: "Provisionamento dos recursos do backend (terraform)"
  jobs:
  - job: Build
    displayName: "BACKEND"

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: |
        docker login -u "rogerferreiracompasso" -p $(dockerpassword)
      displayName: 'docker login'
  
    - script: |
        docker build -t rogerferreiracompasso/$(Build.DefinitionName):v1 .
      displayName: 'docker build'

    - script: |
        docker push rogerferreiracompasso/$(Build.DefinitionName):v1
      displayName: 'docker push'
  

    