trigger:
- master

pool:
  name: 'agentTesteYamaha'

stages:
- stage: Build
  displayName: "Build"
  jobs:
  - job: Build
    displayName: "Build"

    pool:
      name: 'agentTesteYamaha'  

    steps: 
    - task: Docker@0 
      displayName: 'Build an image' 
      inputs:
        imageName: 'teste-registry:latest' 
        azureSubscription: 'testeYamaha' 
        azureContainerRegistry: '{"loginServer":"testeyamaha.azurecr.io", "id" : "/subscriptions/e085391e-3c82-41ab-9e06-ba396884ac18/resourceGroups/TesteYamaha/providers/Microsoft.ContainerRegistry/registries/testeYamaha"}'
        includeLatestTag: true
    - task: Docker@0 
      displayName: 'Push an image' 
      inputs: 
        imageName: 'teste-registry:latest'
        azureSubscription: 'testeYamaha' 
        azureContainerRegistry: '{"loginServer":"testeyamaha.azurecr.io", "id" : "/subscriptions/e085391e-3c82-41ab-9e06-ba396884ac18/resourceGroups/TesteYamaha/providers/Microsoft.ContainerRegistry/registries/testeYamaha"}'
        action: 'Push an image' 
        includeLatestTag: true

  - job: Deploy
    displayName: "Deploy"
    dependsOn: Build

    pool:
      name: 'agentTesteYamaha'

    steps:  
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'kubectl apply -f backend.yml'