# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  - group: libraryTesteYamaha
  - name: buildId
    value: $(Build.BuildId)
  - name: buildName
    value: $(Build.Repository.Name)
stages:
- stage: Build
  displayName: "Build"
  jobs:
  - job: Build
    displayName: "Build"
    
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: |
        docker login -u $(usernameDocker) -p $(passwordDocker)
        echo $(buildId)
        echo $(buildName)
      displayName: 'docker login'
  
    - script: |
        docker build -t $(usernameDocker)/$(buildName):$(buildId) . 
      displayName: 'docker build'

    - script: |
        docker push $(usernameDocker)/$(buildName):$(buildId)
      displayName: 'docker push'
  

    