# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  - group: libraryTesteYamaha
  - name: buildId
    value: $(Build.Repository.Name)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Build
  displayName: "Build"
  jobs:
  - job: Build
    displayName: "Build"
    
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: |
        docker login -u $(usernameDocker) -p $(passwordDocker)
        echo $(buildId)
      displayName: 'docker login'
  
    - script: |
        docker build -t $(usernameDocker)/$(Build.DefinitionName):v2 . 
      displayName: 'docker build'

    - script: |
        docker push $(usernameDocker)/$(Build.DefinitionName):v2
      displayName: 'docker push'
  

    