trigger:
- master

pool:
  name: 'agentTesteYamaha'

stages:
 - stage: Deploy
   jobs:
    - job: Deploy
      displayName: "Deploy"
      
      pool:
        name: 'agentTesteYamaha'

      steps:  
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'kubectl get node'