trigger:
- master
pool:
  vmImage: CSP_Agent
  demands: "Execute kubernetes"
steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'CSP DevOps Connection 2'
    azureResourceGroup: 'RG_AKS_DEV'
    kubernetesCluster: 'aksdevyamaha001'
    command: 'get'
    arguments: 'nodes'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'