apiVersion: apps/v1
kind: Deployment
metadata:
  name: testeyamaha-deployment-v1
spec:
  replicas: 1
  template:  
    metadata:
      name: testeyamaha
      labels:
        app: node-testeyamaha
        version: blue
    spec:
      containers:
        - name: node-container-testeyamaha
          image: testeyamaha.azurecr.io/testeyamahanew:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
               
  selector:
    matchLabels:
      app: node-testeyamaha
