apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-v1
spec:
  replicas: 1
  template:  
    metadata:
      name: backend
      labels:
        app: node-backend
        version: blue
    spec:
      containers:
        - name: node-container-backend
          image: cspyamahaaks.azurecr.io/teste-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
          - configMapRef:
              name: backend-configmap
      imagePullSecrets:
            - name: digital-ocean
  selector:
    matchLabels:
      app: node-backend
